// AUTO-GENERATED by scripts/build-catalog.ts. Do not edit by hand.
// Source: machine_images/MACHINE_MAPPING.json + all_machine_images/manifest.json
// Regenerate with `pnpm catalog`.

export interface RawMachine {
  id: string;
  slug: string;
  name: string;
  rawName: string;
  category: 'labelling' | 'packaging' | 'automation';
  image: string | null;
  gallery: string[];
}

export const MACHINES_RAW: RawMachine[] = [
  {
    "id": "6542366",
    "slug": "continuous-band-sealing-machine",
    "name": "Continuous Band Sealing Machine",
    "rawName": "Continuous_Band_Sealing_Machine",
    "category": "packaging",
    "image": "/products/Continuous_Band_Sealing_Machine_6.png",
    "gallery": [
      "/products/Continuous_Band_Sealing_Machine_6.png",
      "/products/Continuous_Band_Sealing_Machine_0.png",
      "/products/Continuous_Band_Sealing_Machine_3.webp",
      "/products/Continuous_Band_Sealing_Machine_2.webp"
    ]
  },
  {
    "id": "6470625",
    "slug": "flexy-applicator",
    "name": "Flexy Applicator",
    "rawName": "Flexy_Applicator",
    "category": "labelling",
    "image": "/products/Flexy_Applicator_11.png",
    "gallery": [
      "/products/Flexy_Applicator_11.png",
      "/products/Flexy_Applicator_0.png",
      "/products/Flexy_Applicator_12.webp",
      "/products/Flexy_Applicator_2.webp",
      "/products/Flexy_Applicator_3.webp",
      "/products/Flexy_Applicator_4.webp",
      "/products/Flexy_Applicator_6.webp",
      "/products/Flexy_Applicator_5.webp",
      "/products/Flexy_Applicator_7.webp",
      "/products/Flexy_Applicator_8.webp"
    ]
  },
  {
    "id": "6470393",
    "slug": "semi-auto-wrap-around-labelling-machine",
    "name": "Semi Auto Wrap Around Labelling Machine",
    "rawName": "Semi_Auto_Wrap_Around_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Semi_Auto_Wrap_Around_Labelling_Machine_9.png",
    "gallery": [
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_9.png",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_0.png",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_10.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_11.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_2.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_4.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_13.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_3.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_6.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_5.webp",
      "/products/Semi_Auto_Wrap_Around_Labelling_Machine_12.webp"
    ]
  },
  {
    "id": "6470186",
    "slug": "two-side-labelling-machine",
    "name": "Two Side Labelling Machine",
    "rawName": "Two_Side_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Two_Side_Labelling_Machine_8.png",
    "gallery": [
      "/products/Two_Side_Labelling_Machine_8.png",
      "/products/Two_Side_Labelling_Machine_0.png",
      "/products/Two_Side_Labelling_Machine_2.webp",
      "/products/Two_Side_Labelling_Machine_3.webp",
      "/products/Two_Side_Labelling_Machine_9.webp",
      "/products/Two_Side_Labelling_Machine_4.webp",
      "/products/Two_Side_Labelling_Machine_5.webp"
    ]
  },
  {
    "id": "6467488",
    "slug": "custom-top-labelling-machine-with-checking-system",
    "name": "Custom Top Labelling Machine With Checking System",
    "rawName": "Custom_Top_Labelling_Machine_with_Checking_System",
    "category": "labelling",
    "image": "/products/Custom_Top_Labelling_Machine_with_Checking_System_8.png",
    "gallery": [
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_8.png",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_2.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_0.png",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_3.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_9.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_5.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_4.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_12.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_10.webp",
      "/products/Custom_Top_Labelling_Machine_with_Checking_System_11.webp"
    ]
  },
  {
    "id": "6464930",
    "slug": "two-in-one-wrap-around-side-labelling-machine",
    "name": "Two In One Wrap Around Side Labelling Machine",
    "rawName": "Two_in_One_Wrap_Around_Side_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_8.png",
    "gallery": [
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_8.png",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_0.png",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_2.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_3.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_10.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_9.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_12.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_4.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_5.webp",
      "/products/Two_in_One_Wrap_Around_Side_Labelling_Machine_11.webp"
    ]
  },
  {
    "id": "6464798",
    "slug": "print-apply-top-labelling-machine",
    "name": "Print Apply Top Labelling Machine",
    "rawName": "Print_Apply_Top_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Print_Apply_Top_Labelling_Machine_10.png",
    "gallery": [
      "/products/Print_Apply_Top_Labelling_Machine_10.png",
      "/products/Print_Apply_Top_Labelling_Machine_0.png",
      "/products/Print_Apply_Top_Labelling_Machine_11.webp",
      "/products/Print_Apply_Top_Labelling_Machine_4.webp",
      "/products/Print_Apply_Top_Labelling_Machine_14.webp",
      "/products/Print_Apply_Top_Labelling_Machine_5.webp",
      "/products/Print_Apply_Top_Labelling_Machine_2.webp",
      "/products/Print_Apply_Top_Labelling_Machine_12.webp",
      "/products/Print_Apply_Top_Labelling_Machine_6.webp",
      "/products/Print_Apply_Top_Labelling_Machine_3.webp",
      "/products/Print_Apply_Top_Labelling_Machine_7.webp",
      "/products/Print_Apply_Top_Labelling_Machine_13.webp"
    ]
  },
  {
    "id": "6463899",
    "slug": "one-side-wrap-around-side-labelling-machine",
    "name": "One Side Wrap Around Side Labelling Machine",
    "rawName": "One_Side_Wrap_Around_Side_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6462872",
    "slug": "top-labelling-machine-with-thermal-transfer-printer-auto-feeder",
    "name": "Top Labelling Machine With Thermal Transfer Printer Auto Feeder",
    "rawName": "Top_Labelling_Machine_with_Thermal_Transfer_Printer_Auto_Feeder",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461971",
    "slug": "bottom-labelling-machine",
    "name": "Bottom Labelling Machine",
    "rawName": "Bottom_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461970",
    "slug": "print-apply-labeller",
    "name": "Print Apply Labeller",
    "rawName": "Print_Apply_Labeller",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461969",
    "slug": "flat-labelling-machine",
    "name": "Flat Labelling Machine",
    "rawName": "Flat_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461968",
    "slug": "top-labelling-machine",
    "name": "Top Labelling Machine",
    "rawName": "Top_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461967",
    "slug": "top-labelling-machine-with-thermal-transfer-printer-auto-feeder-v2",
    "name": "Top Labelling Machine With Thermal Transfer Printer Auto Feeder V2",
    "rawName": "Top_Labelling_Machine_with_Thermal_Transfer_Printer_Auto_Feeder_v2",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461966",
    "slug": "customized-bottom-labelling-machine",
    "name": "Customized Bottom Labelling Machine",
    "rawName": "Customized_Bottom_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461965",
    "slug": "egg-tray-labelling-machine",
    "name": "Egg Tray Labelling Machine",
    "rawName": "Egg_Tray_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461964",
    "slug": "three-side-labelling-machine",
    "name": "Three Side Labelling Machine",
    "rawName": "Three_Side_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461963",
    "slug": "body-neck-labelling-machine",
    "name": "Body Neck Labelling Machine",
    "rawName": "Body_Neck_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461962",
    "slug": "top-labelling-machine-v2",
    "name": "Top Labelling Machine V2",
    "rawName": "Top_Labelling_Machine_v2",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461961",
    "slug": "top-labelling-machine-with-corner-press-device",
    "name": "Top Labelling Machine With Corner Press Device",
    "rawName": "Top_Labelling_Machine_with_Corner_Press_Device",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461960",
    "slug": "front-back-labelling-machine",
    "name": "Front Back Labelling Machine",
    "rawName": "Front_Back_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "6461959",
    "slug": "vertical-wrap-around-labelling-machine",
    "name": "Vertical Wrap Around Labelling Machine",
    "rawName": "Vertical_Wrap_Around_Labelling_Machine",
    "category": "labelling",
    "image": null,
    "gallery": []
  },
  {
    "id": "4788377",
    "slug": "two-side-labelling-machine-with-corner-press",
    "name": "Two Side Labelling Machine With Corner Press",
    "rawName": "Two_Side_Labelling_Machine_with_Corner_Press",
    "category": "labelling",
    "image": "/products/Two_Side_Labelling_Machine_with_Corner_Press_0.png",
    "gallery": [
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_0.png",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_3.webp",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_12.webp",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_2.webp",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_11.webp",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_13.webp",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_6.png",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_10.webp",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_9.png",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_7.png",
      "/products/Two_Side_Labelling_Machine_with_Corner_Press_8.png"
    ]
  },
  {
    "id": "4788373",
    "slug": "customized-top-labelling-machine",
    "name": "Customized Top Labelling Machine",
    "rawName": "Customized_Top_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Customized_Top_Labelling_Machine_0.png",
    "gallery": [
      "/products/Customized_Top_Labelling_Machine_0.png",
      "/products/Customized_Top_Labelling_Machine_13.webp",
      "/products/Customized_Top_Labelling_Machine_14.webp",
      "/products/Customized_Top_Labelling_Machine_16.webp",
      "/products/Customized_Top_Labelling_Machine_9.png",
      "/products/Customized_Top_Labelling_Machine_4.webp",
      "/products/Customized_Top_Labelling_Machine_2.webp",
      "/products/Customized_Top_Labelling_Machine_10.png",
      "/products/Customized_Top_Labelling_Machine_3.webp",
      "/products/Customized_Top_Labelling_Machine_12.png",
      "/products/Customized_Top_Labelling_Machine_15.webp",
      "/products/Customized_Top_Labelling_Machine_11.png",
      "/products/Customized_Top_Labelling_Machine_8.jpg",
      "/products/Customized_Top_Labelling_Machine_7.jpg"
    ]
  },
  {
    "id": "4788368",
    "slug": "semi-auto-round-bottle-labelling-machine",
    "name": "Semi Auto Round Bottle Labelling Machine",
    "rawName": "Semi_Auto_Round_Bottle_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Semi_Auto_Round_Bottle_Labelling_Machine_0.png",
    "gallery": [
      "/products/Semi_Auto_Round_Bottle_Labelling_Machine_0.png",
      "/products/Semi_Auto_Round_Bottle_Labelling_Machine_7.webp",
      "/products/Semi_Auto_Round_Bottle_Labelling_Machine_5.webp",
      "/products/Semi_Auto_Round_Bottle_Labelling_Machine_6.webp",
      "/products/Semi_Auto_Round_Bottle_Labelling_Machine_8.webp",
      "/products/Semi_Auto_Round_Bottle_Labelling_Machine_2.webp"
    ]
  },
  {
    "id": "4788365",
    "slug": "standard-top-labelling-machine",
    "name": "Standard Top Labelling Machine",
    "rawName": "Standard_Top_Labelling_Machine",
    "category": "labelling",
    "image": "/products/Standard_Top_Labelling_Machine_0.png",
    "gallery": [
      "/products/Standard_Top_Labelling_Machine_0.png",
      "/products/Standard_Top_Labelling_Machine_13.webp",
      "/products/Standard_Top_Labelling_Machine_16.webp",
      "/products/Standard_Top_Labelling_Machine_9.png",
      "/products/Standard_Top_Labelling_Machine_3.webp",
      "/products/Standard_Top_Labelling_Machine_2.webp",
      "/products/Standard_Top_Labelling_Machine_14.webp",
      "/products/Standard_Top_Labelling_Machine_4.webp",
      "/products/Standard_Top_Labelling_Machine_12.png",
      "/products/Standard_Top_Labelling_Machine_10.png",
      "/products/Standard_Top_Labelling_Machine_11.png",
      "/products/Standard_Top_Labelling_Machine_7.webp",
      "/products/Standard_Top_Labelling_Machine_8.webp",
      "/products/Standard_Top_Labelling_Machine_15.webp"
    ]
  },
  {
    "id": "4788353",
    "slug": "ar600-3d-printer",
    "name": "AR600 3D Printer",
    "rawName": "AR600_3D_Printer",
    "category": "automation",
    "image": null,
    "gallery": []
  },
  {
    "id": "4788352",
    "slug": "ar320-3d-printer",
    "name": "AR320 3D Printer",
    "rawName": "AR320_3D_Printer",
    "category": "automation",
    "image": null,
    "gallery": []
  },
  {
    "id": "4788349",
    "slug": "ar220-3d-printer",
    "name": "AR220 3D Printer",
    "rawName": "AR220_3D_Printer",
    "category": "automation",
    "image": null,
    "gallery": []
  },
  {
    "id": "4788387",
    "slug": "continuous-band-sealing-machine-v2",
    "name": "Continuous Band Sealing Machine V2",
    "rawName": "Continuous_Band_Sealing_Machine_v2",
    "category": "packaging",
    "image": null,
    "gallery": []
  }
];
