/**
 * Generates lib/catalog.generated.ts from source-of-truth files:
 *   - ../all_machine_images/manifest.json   (per-machine file list + sizes)
 *   - ../machine_images/MACHINE_MAPPING.json (canonical 30-machine list)
 *   - public/products/                      (filesystem verification)
 *
 * Run via `pnpm catalog` (or automatically on `pnpm prebuild`).
 *
 * Output is committed to the repo so production builds don't need the
 * source files. Re-run whenever new photography is added.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const PUBLIC_PRODUCTS = path.join(ROOT, 'public', 'products');
const MAPPING_PATH = path.resolve(ROOT, '..', 'machine_images', 'MACHINE_MAPPING.json');
const MANIFEST_PATH = path.resolve(ROOT, '..', 'all_machine_images', 'manifest.json');
const OUTPUT = path.join(ROOT, 'lib', 'catalog.generated.ts');

const MIN_COVER_BYTES = 30_000; // ≈ 30KB — filters out CDN micro-thumbnails

type RawCategory = 'Labelling' | 'Packaging' | '3D_Printer';
interface MappingMachine {
  name: string;
  id: string;
  category: RawCategory;
}
interface MappingFile {
  machines: MappingMachine[];
}

interface ManifestImage {
  filename: string;
  url: string;
  size: number;
}
interface ManifestFile {
  images: Record<string, ManifestImage[]>;
}

interface GeneratedMachine {
  id: string;
  slug: string;
  name: string;
  rawName: string;
  category: 'labelling' | 'packaging' | 'automation';
  image: string | null;
  gallery: string[];
}

function pascalToTitle(s: string): string {
  return s
    .replace(/_v(\d+)/g, ' v$1')
    .replace(/_/g, ' ')
    .replace(/\b(\w)/g, (_, c) => c.toUpperCase())
    .replace(/\bv(\d+)/g, 'v$1');
}

function toSlug(s: string): string {
  return s
    .toLowerCase()
    .replace(/_/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function mapCategory(c: RawCategory): GeneratedMachine['category'] {
  if (c === 'Labelling') return 'labelling';
  if (c === 'Packaging') return 'packaging';
  return 'automation';
}

function buildOne(
  m: MappingMachine,
  manifestEntry: ManifestImage[] | undefined,
): GeneratedMachine {
  const base: GeneratedMachine = {
    id: m.id,
    slug: toSlug(m.name),
    name: pascalToTitle(m.name),
    rawName: m.name,
    category: mapCategory(m.category),
    image: null,
    gallery: [],
  };

  if (!manifestEntry || manifestEntry.length === 0) return base;

  // Filter to files that actually exist on disk + dedupe by upstream URL
  // (the manifest sometimes lists the same source URL twice — e.g. the
  // first two entries of Continuous_Band_Sealing_Machine both point to
  // np_25558_1702606652.png with the same size).
  const seenUrls = new Set<string>();
  const present = manifestEntry.filter((img) => {
    const onDisk = fs.existsSync(path.join(PUBLIC_PRODUCTS, img.filename));
    if (!onDisk) {
      console.warn(`  · missing on disk: ${img.filename}`);
      return false;
    }
    if (seenUrls.has(img.url)) return false;
    seenUrls.add(img.url);
    return true;
  });

  if (present.length === 0) return base;

  // Sort by size desc — the biggest file is almost always the hero shot.
  const sorted = [...present].sort((a, b) => b.size - a.size);

  // Cover = the largest file ≥ MIN_COVER_BYTES, else just the largest.
  const cover =
    sorted.find((img) => img.size >= MIN_COVER_BYTES) ?? sorted[0];

  const gallery = [cover, ...sorted.filter((img) => img !== cover)].map(
    (img) => `/products/${img.filename}`,
  );

  return {
    ...base,
    image: `/products/${cover.filename}`,
    gallery,
  };
}

function main(): void {
  console.log('▶ build-catalog: reading sources');

  // Source files live OUTSIDE the repo root (one level up). They're only
  // present on the maintainer's local machine where photography is staged.
  // In CI/CD (Vercel, GitHub Actions, etc.) just trust the committed
  // lib/catalog.generated.ts — exit 0 cleanly instead of failing the build.
  if (!fs.existsSync(MAPPING_PATH) || !fs.existsSync(MANIFEST_PATH)) {
    console.log(
      '  · source manifests not present (expected in CI) — using committed lib/catalog.generated.ts',
    );
    return;
  }

  const mapping = JSON.parse(fs.readFileSync(MAPPING_PATH, 'utf-8')) as MappingFile;
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8')) as ManifestFile;

  console.log(`  · ${mapping.machines.length} machines in mapping`);
  console.log(`  · ${Object.keys(manifest.images).length} machines in manifest`);

  const generated = mapping.machines.map((m) =>
    buildOne(m, manifest.images[m.name]),
  );

  const photographed = generated.filter((g) => g.image !== null).length;
  const totalShots = generated.reduce((n, g) => n + g.gallery.length, 0);

  console.log(`  · ${photographed}/${generated.length} machines with cover image`);
  console.log(`  · ${totalShots} total verified shots`);

  const banner = `// AUTO-GENERATED by scripts/build-catalog.ts. Do not edit by hand.
// Source: machine_images/MACHINE_MAPPING.json + all_machine_images/manifest.json
// Regenerate with \`pnpm catalog\`.
`;

  const body = `
export interface RawMachine {
  id: string;
  slug: string;
  name: string;
  rawName: string;
  category: 'labelling' | 'packaging' | 'automation';
  image: string | null;
  gallery: string[];
}

export const MACHINES_RAW: RawMachine[] = ${JSON.stringify(generated, null, 2)};
`;

  fs.writeFileSync(OUTPUT, banner + body);
  console.log(`✔ wrote ${path.relative(ROOT, OUTPUT)}`);
}

main();
